# nav2_params.yaml
# Parameters for Nav2 bringup (navigation + SLAM integration)

# Use simulation time? Overridden by launch argument.
use_sim_time: false

# Global planner plugin
planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.3

# Controller (local planner) plugin
controller_server:
  ros__parameters:
    expected_controller_frequency: 20.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      # DWB params:
      odom_topic: "odom"
      global_frame: "map"
      robot_base_frame: "base_link"
      use_sim_time: false
      critic_plugins: ["Oscillation", "Progress", "GoalAlign", "GoalDist", "PathAlign", "PathDist"]
      Oscillation:
        plugin: "dwb_critics::Oscillation"
      Progress:
        plugin: "dwb_critics::Progress"
      GoalAlign:
        plugin: "dwb_critics::AlignGoal"
      GoalDist:
        plugin: "dwb_critics::DistToGoal"
      PathAlign:
        plugin: "dwb_critics::AlignPath"
      PathDist:
        plugin: "dwb_critics::DistToPath"

# Recovery behaviors
recoveries_server:
  ros__parameters:
    expected_recovery_frequency: 2.0
    recovery_plugins: ["spin"]
    spin:
      plugin: "nav2_recoveries/Spin"
      spin_duration: 3.0
      spin_namespace: ""

# Behavior tree for navigation
bt_navigator:
  ros__parameters:
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

# Costmap parameters
global_costmap:
  ros__parameters:
    global_frame: "map"
    robot_base_frame: "base_link"
    update_frequency: 1.0
    publish_frequency: 0.5
    rolling_window: false
    width: 10.0
    height: 10.0
    resolution: 0.05
    use_sim_time: false
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_topic: "map"
      subscribe_to_updates: false
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      scan_topic: "scan"
      observation_sources: "scan"
      scan:
        data_type: LaserScan
        topic: "scan"
        marking: true
        clearing: true
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.2

local_costmap:
  ros__parameters:
    global_frame: "odom"
    robot_base_frame: "base_link"
    update_frequency: 10.0
    publish_frequency: 5.0
    rolling_window: true
    width: 6.0
    height: 6.0
    resolution: 0.05
    use_sim_time: false
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      scan_topic: "scan"
      observation_sources: "scan"
      scan:
        data_type: LaserScan
        topic: "scan"
        marking: true
        clearing: true
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.2

# Recovery server (optional)
recoveries_server:
  ros__parameters:
    recovery_plugins: ["spin", "back_up"]
    spin:
      plugin: "nav2_recoveries/Spin"
      spin_duration: 4.0
    back_up:
      plugin: "nav2_recoveries/BackUp"
      backup_distance: 0.5

# Lifecycle manager for Nav2
lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      - "controller_server"
      - "planner_server"
      - "recoveries_server"
      - "bt_navigator"
      - "global_costmap"
      - "local_costmap"
